name: "KiCad Release"

on:
  push:
    tags:
      - 'v*.*'

jobs:
  Release:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:1.7.0
    steps:
    - name: Setting up the environment
      run: |
        apt update
        apt -y install zip rename
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Building production files
      run: |
        for arg in ./hardware*; do sed -i "s/VERV/${GITHUB_REF_NAME}/" ${arg}/*.kicad_*; \
        .github/scripts/KiExport.sh -n ${GITHUB_REPOSITORY#*/}_`basename $arg` -v ${GITHUB_REF_NAME} -k $arg -o manufacturing -s -p -g -c -a -b -i; done
    - name: Building production files
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.date.outputs.yymmdd }}
        files: manufacturing/*
